ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  # config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "master" do |node|

    node.vm.box               = "bento/centos-7.7"
    node.vm.box_check_update  = false
    node.vm.hostname          = "master.local.com"

    node.vm.network "public_network", ip: "192.168.0.100"

    node.vm.provider :virtualbox do |v|
      v.name    = "master"
      v.memory  = 2048
      v.cpus    =  2
    end

    node.vm.provider :libvirt do |v|
      v.memory  = 2048
      v.nested  = true
      v.cpus    = 2
    end

    # node.vm.provision "shell", path: "bootstrap_kmaster.sh"

    node.vm.provision "shell",
      run: "always",
      inline: "route add default gw 192.168.0.1"
    # node.vm.provision "shell", path: "bootstrap_kmaster.sh"

  # delete default gw on eth0
    node.vm.provision "shell",
      run: "always",
      inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
  end


  # Kubernetes Worker Nodes
  NodeCount = 2

  (1..NodeCount).each do |i|

    config.vm.define "worker#{i}" do |node|

      node.vm.box               = "bento/centos-7.7"
      node.vm.box_check_update  = false
      node.vm.hostname          = "worker#{i}.local.com"

      node.vm.network "public_network", ip: "192.168.0.10#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "worker#{i}"
        v.memory  = 1024
        v.cpus    = 1

      node.vm.provision "shell",
        run: "always",
        inline: "route add default gw 192.168.0.1"
      # node.vm.provision "shell", path: "bootstrap_kmaster.sh"
  
      # delete default gw on eth0
      node.vm.provision "shell",
        run: "always",
        inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
      end
